# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NDProtoTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NDProtoTest
  pod "Protobuf"
  pod "YYModel"
  pod "MJExtension"

  target 'NDProtoTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
